services:

  nginx:
    build: ./nginx
    ports:
        - '80:80'
    volumes:
        - ./log/nginx:/var/log/nginx
        - ./sites:/var/www/html
    links:
        - wordpress
    restart: always

  mysql:
    image: mysql:latest
    ports:
        - '3306:3306'
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    
  wordpress:
    build: ./php
    ports:
        - '9000:9000'
    volumes:
        - ./sites:/var/www/html
    environment:
        WORDPRESS_DB_NAME: ${DATABASE}
        WORDPRESS_DB_USER: ${MYSQL_USER}
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    links:
        - mysql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1