services:

  nginx:
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./nginx:/var/log/nginx
        - ./sites:/var/www/html
    links:
        - wordpress
    restart: always

  mysql:
    image: mysql:latest
    env_file:
     - mysql.env
    ports:
        - '3306:3306'
    volumes:
        - ./mysql:/var/lib/mysql
    restart: always
    
  wordpress:
    image: wordpress:php8.3-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./sites:/var/www/html
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
        WORDPRESS_DB_NAME: dbase
        WORDPRESS_DB_USER: dadenard
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_PASSWORD: Admin624600@
    links:
        - mysql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1